---
- name: install snapd packages
  package:
    name: snapd
    state: present
  register: snapd_install

- name: ln /snap to enable classic support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: restart system if snapd installed
  reboot:
  when: snapd_install.changed is true
