---
- name: create Microsoft yum repo
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: yes
  tags:
    - install
    - vscode

- name: Install VS Code
  package:
    name: code
    state: present
  tags:
    - install
    - vscode
