acropolis:
  hosts:
    localhost:
  vars:
    ansible_connection: local
    extrapkgs:
      - git
      - ansible
      - cowsay
      - virt-manager
      - nmap
      - vagrant
      - gnome-tweaks

empire:
  hosts:
    192.168.1.5:
  vars:
    extrapkgs:
      - vagrant
      - nmap

all:
  vars:
    localuser: piechota

