---
- name: common init
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - systemupdate
    - extrapkgs

- name: Acropolis initialization
  hosts: acropolis
  become: yes
  become_method: sudo

  roles:
    - capslock
    - snapd
    - vscode
#    - zoom

- name: Empire initialization
  hosts: empire
  become: yes
  become_method: sudo

  roles:
#    - cockpit
#    - libvirt
